apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-devops-sandbox-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sandbox
  template:
    metadata:
      labels:
        app: sandbox
    spec:
      containers:
        - name: sandbox
          image: gcp-devops-sandbox:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000