apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sandbox-monitor
  namespace: monitoring
  labels:
    release: monitoring-stack
spec:
  selector:
    matchLabels:
      app: sandbox
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      interval: 10s