apiVersion: v1
kind: Service
metadata:
  name: gcp-devops-sandbox-service
  labels:
    app: sandbox
spec:
  type: NodePort
  selector:
    app: sandbox
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30001